// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZy0_E-HVLEZk34mmyELpqMmPUHNpMjjc',
    appId: '1:594181132108:web:18f9e180e201cdb7b909e9',
    messagingSenderId: '594181132108',
    projectId: 'jq4b-memv-2024-alm',
    authDomain: 'jq4b-memv-2024-alm.firebaseapp.com',
    storageBucket: 'jq4b-memv-2024-alm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7KY43D_rvINB_13u2pioV12rju7TlpeQ',
    appId: '1:594181132108:android:138ea95ad36dc7feb909e9',
    messagingSenderId: '594181132108',
    projectId: 'jq4b-memv-2024-alm',
    storageBucket: 'jq4b-memv-2024-alm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACrTgP96UsXvoT80Pqfj4goDifmSyKZ2g',
    appId: '1:594181132108:ios:1acae6efb580d00eb909e9',
    messagingSenderId: '594181132108',
    projectId: 'jq4b-memv-2024-alm',
    storageBucket: 'jq4b-memv-2024-alm.firebasestorage.app',
    iosBundleId: 'com.example.inventarioProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACrTgP96UsXvoT80Pqfj4goDifmSyKZ2g',
    appId: '1:594181132108:ios:1acae6efb580d00eb909e9',
    messagingSenderId: '594181132108',
    projectId: 'jq4b-memv-2024-alm',
    storageBucket: 'jq4b-memv-2024-alm.firebasestorage.app',
    iosBundleId: 'com.example.inventarioProyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsloTYbd_YW5xnpcKidQODkmLkZtzGA7Q',
    appId: '1:594181132108:web:08d74a98de469ba4b909e9',
    messagingSenderId: '594181132108',
    projectId: 'jq4b-memv-2024-alm',
    authDomain: 'jq4b-memv-2024-alm.firebaseapp.com',
    storageBucket: 'jq4b-memv-2024-alm.firebasestorage.app',
  );
}
